InvestAssist/InvestAssist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),   
]

InvestAssist/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'), 
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),      
]

InvestAssist/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('<int:pk>', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

InvestAssist/core/models.py
from django.db import models

class Item(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

InvestAssist/item/models.py
from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

InvestAssist/core/forms.py
from django import forms
from django .contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
     username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Seu nome de usuário',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
     
     password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Sua senha',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Seu nome de usuário',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Seu e-mail',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Sua senha',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repita a senha  ',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

InvestAssist/item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-30 py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = ('name',)

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            })
        }

InvestAssist/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as auth_logout
from django.core.mail import send_mail


from item.models import Item 
from .forms import SignupForm

def index(request):
    items = Item.objects.all()

    return render(request, 'core/index.html', {
        'items': items,
    })

from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.core.mail import send_mail
from .forms import SignupForm

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()

            # Enviar o e-mail de confirmação
            send_mail(
                'Confirmação de Cadastro',
                f'Olá {user.username}, obrigado por se cadastrar em nossa aplicação InvestAssist.',
                'seuemail@example.com',  # Remetente do e-mail
                [user.email],  # Destinatário do e-mail
                fail_silently=False,
            )

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })


def logout(request):
    auth_logout(request)
    return redirect('core:index')

InvestAssist/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Item
from .forms import NewItemForm


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)

    return render(request, 'item/detail.html', {
        'item': item
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Novo ativo',
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk,)
    item.delete()

    return redirect('core:index')

InvestAssist/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>

    <title>{% block title %}{% endblock %} | InvestAssist </title>
</head>

<body>

    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-300">
        <a href="/" class="text-xl font-semibold">InvestAssist</a>
    
        <div>
            {% if request.user.is_authenticated %}
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">Novo item</a>
                <a href="{% url 'core:logout'  %}" class="px-6 py-3 text-lg font-semibold bg-stone-500 text-white rounded-xl hover:bg-stone-700">Sair</a>
            {% else %}
                <a href="{% url 'core:signup'  %}" class="px-6 py-3 text-lg font-semibold bg-stone-500 text-white rounded-xl hover:bg-stone-700">Cadastre-se</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Entrar</a>
            {% endif %}
        </div>
    </nav>
    

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>
 

</body>

</html>

InvestAssist/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Bem-vindo{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">Seus ativos</h2>

            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <p class="text-center mt-6"><strong>Faça login para ver seus ativos ou cadastre-se.</strong></p>
    {% endif %}
{% endblock %}

InvestAssist/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Entrar{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Entrar</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Nome de usuário:</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Senha:</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}

            </div>
            {% endif %}

        <button class="mt-6 py-4 px-8 text-lg bg-gray-500 hover:bg-gray-700 rounded-xl text-white">Entrar</button>
    </form>
</div>
{% endblock %}

InvestAssist/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Cadastre-se{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Cadastre-se</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Nome de usuário:</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">E-mail:</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Senha:</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repita a senha:</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}

            </div>
            {% endif %}

        <button class="mt-6 py-4 px-8 text-lg bg-stone-500 hover:bg-stone-700 rounded-xl text-white">Cadastrar</button>
    </form>
</div>
{% endblock %}

InvestAssist/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <p><strong>{{ item.name }}</strong></p>

    {% if request.use == item.created_by %}
    <div class="mt-6 p-6 bg-white rounded-xl">
        <p>Esse é o seu ativo!</p>

        <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Excluir</a>
    </div>
    {% endif %}
</div>
{%  endblock %}

 

InvestAssist/item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}o{% endblock %}

{% block content %}
 <h1 class="mb-6 text-3xl">{{ title }}</h1>
    
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="space-y-4">
            {{ form.as_p}}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
        {% endif %}
    
    <button class="mt-6 py-4 px-8 text-lg bg-stone-500 hover:bg-stone-700 rounded-xl text-white">Adicionar</button>
  </form>
{% endblock %}